-- schema.sql
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  phone VARCHAR(50) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE otps (
  id SERIAL PRIMARY KEY,
  phone VARCHAR(50) NOT NULL,
  otp VARCHAR(6) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- seed.sql
INSERT INTO users (phone) VALUES ('9876543210'), ('user@example.com');
INSERT INTO otps (phone, otp) VALUES ('9876543210', '123456');
